# Python - Numpy 

In [55]:
import cv2
import numpy as np


In [12]:
image = cv2.imread('./image.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
result = np.zeros((image.shape[0], 256), dtype=np.uint8)

hist = cv2.calcHist([image],[0],None,[256],[0,256])
cv2.normalize(hist, hist, 0, 256, cv2.NORM_MINMAX)

for x, y in enumerate(hist):
    cv2.line(result, (x, image.shape[0]), (x, image.shape[0]-y), 255)
    
dst = np.hstack([image[:,:,0],result])
cv2.imshow("dst",dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
array1 = np.array([[1,2,3], [4,5,6]])
array2 = np.array([1,2,3], dtype=complex, ndmin=3)

array4 = np.array(np.mat('1 2; 3 4'), subok=True)

array1[0] = [4,5,6]


print(array1)
print(array2)
print(array4)

[[4 5 6]
 [4 5 6]]
[[[1.+0.j 2.+0.j 3.+0.j]]]
[[1 2]
 [3 4]]


In [18]:
array = np.array([[1,2,3,4,5],
                 [6,7,8,9,10],
                 [11,12,13,14,15],
                 [16,17,18,19,20]])

print(array[1:3])
print(array[::2])
print(array[2, 1::2])

[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[12 14]


In [20]:
array = np.arange(12)

reshape1 = array.reshape(2,3,2)
reshape2 = np.reshape(array, (2,-1), order='F')

print(reshape1)
print(reshape2)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [34]:
array = np.arange(4)

axis1 = array[np.newaxis]
axis2 = array[:, np.newaxis]


flat1 = axis2.flatten(order='F')
print(array)
print(axis1)
print(axis2)
print(flat1)

[0 1 2 3]
[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]
[0 1 2 3]


In [38]:
array1 = np.arange(6).reshape(2,3)
array2 = np.arange(6, 12).reshape(2,3)

merge1 = np.stack([array1, array2], axis=0)
merge2 = np.stack([array1, array2], axis=-1)

print(merge1)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [39]:
print(merge2)

[[[ 0  6]
  [ 1  7]
  [ 2  8]]

 [[ 3  9]
  [ 4 10]
  [ 5 11]]]


In [49]:
array = np.arange(10).reshape(2,5)

detach1 = np.split(array, 2, axis=0)
detach2 = np.split(array, [2,3], axis=1)

print(array)
print(detach1)
print(detach2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]
[array([[0, 1],
       [5, 6]]), array([[2],
       [7]]), array([[3, 4],
       [8, 9]])]


In [53]:
array1 = np.array([1,2,3,4]).reshape(2,2)
array2 = np.array([1.5, 2.5])
print(array1)

add = array1 + array2
print(add)

[[1 2]
 [3 4]]
[[2.5 4.5]
 [4.5 6.5]]


In [57]:
array = np.zeros((1280, 1920, 3), np.uint8)
x,y,w,h = 100, 100, 300, 300
roi = array[x:x+w, y:y+h]

print(array.shape)
print(roi.shape)

(1280, 1920, 3)
(300, 300, 3)


# OpenCV Example

## 1. 이미지 입력

#### cv2.imread(이미지 경로, 플래그:이미지 입력 함수의 플래그)

In [59]:
src = cv2.imread("./image.jpg", cv2.IMREAD_GRAYSCALE)

print(src.ndim, src.shape, src.dtype)
print(src)

2 (863, 1300) uint8
[[118  91 136 ... 237 237 237]
 [109 102 109 ... 238 238 238]
 [129 147 121 ... 238 238 238]
 ...
 [160 145 135 ...  51  47  40]
 [ 99 141 146 ...  46  44  37]
 [ 45 132 163 ...  44  45  42]]


## 2. 이미지 출력

In [61]:
cv2.namedWindow("src", flags = cv2.WINDOW_FREERATIO)
cv2.resizeWindow("src", 400, 200)
cv2.imshow("src",src)
cv2.waitKey(0)
cv2.destroyWindow("src")


cv2.namedWindow(winname, flags=None): 화면에 이미지를 표시할 수 있는 윈도우를 생성.</p>
cv2.resizeWindow(winname, width, height): winname과 동일한 윈도우의 크기를 설정.</p>
cv2.imshow(winname, ndarray): 윈도우에 이미지를 표시.</p>
cv2.waitKey(int delay): 지정된 시간 동안 키 입력이 있을 때까지 프로그램을 지연시킴.</p>
cv2.destroyWindow(string winName): 윈도우를 제거.</p>

## 3. 동영상 출력

In [64]:
capture = cv2. VideoCapture("./count.mp4")

while True:
    ret, frame = capture.read()
    
    if(capture.get(cv2.CAP_PROP_POS_FRAMES) == capture.get(cv2.CAP_PROP_FRAME_COUNT)):
        capture.open('./count.mp4')
        
    cv2.imshow("VideoFrame", frame)
    if cv2.waitKey(33) == ord('q'): break  # 키보드에서 q를 누르면 동영상 출력이 종료됨.
        
capture.release()
cv2.destroyAllWindows()

while문: 동영상에서 프레임을 모두 표시하기 위해 사용. </p>
capture.read(): 동영상 파일에서 프레임을 가져와서 압축을 해제한 다음 bool과 ndarray 타입의 값을 반환.</p>
- ret(bool)은 capture 변수에서 정상적으로 프레임을 읽었는지를 나타내고, frame(ndarray)은 현재 프레임을 나타낸다. </p>

현재 프레임수(cv2.CAP_PROP_POS_FRAMES)가 동영상의 총 프레임 수(cv2.CAP_PROP_FRAME_COUNT)와 동일할 때 동영상 파일을 다시 읽어서 capture 변수에 동영상을 할당 or break문을 통해 반복문 종료. </p>

cv2.imshow(): 이미지로 저장된 프레임을 윈도우에 표시.</p>
- 이를 위해 cv2.waitKey()를 사용하여 33ms만큼 대기한 후, 다음 프레임으로 넘어가게 함.
- Python OpenCV는 문자를 처리하지 못하므로, 유니코드 값으로 변환하기 위해 ord()를 활용. </p>

capture.release(): 동영상 재생이 끝나면 동영상 파일을 닫고 메모리르 해제하기 위해 호출.</p>
cv2.destroyAllWindows(): 모든 윈도우를 제거 (동영상 파일의 재생이 끝났기 때문에)


# 4. 카메라 출력
카메라가 스트리밍 형태로 동작할 때 사용. 즉, 데이터를 실시간으로 받아오고 분석해야 하는 경우 카메라를 이용해 데이터를 처리, </p>
- Python OpenCVSharp의 카메라 출력 클래스

In [ ]:
captrue = cv2.VideoCapture(index)   #index: 카메라의 장치 번호.

웹캡이 내장된 노트북이나 내장돼 있지 않은 컴퓨터에 카메라를 연결할 경우 장치 번호는 0. </p>
카메라가 여러 대 연결돼 있다면 0이 아닌 1, 2, 3, ... 등의 장치 번호를 사용하여 외부 카메라 사용 가능.